name: Publish Docker Image
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: [3.8.8, 3.9.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Config
        run: |
          echo ${{ github.event.release.tag_name }} >> ${GITHUB_ENV}
          echo ${{ matrix.py }} >> ${GITHUB_ENV}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: dockerfile/Dockerfile
          push: true
          tags: khirotaka0122/torch:${{ env.tag }}-aarch64-py${{ env.py-version }}
          build-args: PYTHON_VERSION=${{ matrix.py }} TORCH_VERSION=${{ env.tag }}

